[package]
name = "terminal_print"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
lru = "0.12.3"
# Other dependencies here

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "benchmark"
harness = false
